name = "billum"
compatibility_date = "2024-01-25"
pages_build_output_dir = "dist"

[env.production]
route = { pattern = "billum.pages.dev", zone_name = "billum.pages.dev" }

[[env.production.routes]]
pattern = "billum.pages.dev/*" 